### ISSUE TITLE
Script to merge objects from 3 qc steps

### ISSUE THREAD

**Issue by AntoniaChroni** [kids-first/kf-dev-single-cell-rna#34]
We will replace the `seurat_merge.R` script with another that 

- merges seurat objects from 3 qc steps

This is assigned to @AntoniaChroni.

**Comment by AntoniaChroni** [comment]
This is being addressed in the PR https://github.com/kids-first/kf-dev-single-cell-rna/pull/33
After a discussion with @migbro, he recommended converting the notebook into an R script for Docker convenience. @dmiller15 will work on this.

**Comment by dmiller15** [comment]
The script is available in this PR: https://github.com/kids-first/kf-dev-single-cell-rna/pull/38

Specifically: https://github.com/kids-first/kf-dev-single-cell-rna/blob/ffe50770c88522968b1cddfbe3008f6635ce2063/scripts/seurat_filter.R
